### ISSUE TITLE
Cameras with®in the name fail

### ISSUE THREAD

**Issue by ajobbins** [jpalbert/logitech-webcam-dialog#3]
My target camera is called "Microsoft® LifeCam Studio(TM)" but placing this in the 'webcamdialog.bat' file resulted in the following error:
```
[dshow @ 0000017322b5bd00] Could not find video device with name [Microsoft� LifeCam Studio(TM)] among source devices of type video.
video=Microsoft� LifeCam Studio(TM): I/O error
```

Suspect it has something to do with the chcp command at line 1. Was able to work around by using the Alternative name for the device instead

**Comment by jpalbert** [comment]
The CHCP command should resolve your issue. Looking at your error, it looks like the ® wasn't encoded properly. What are you using to edit the file?

**Comment by ajobbins** [comment]
Thanks. Originally saved in Notepad. Re did in Notepad++ and now working
