### ISSUE TITLE
Output File Error

### ISSUE THREAD

**Issue by hysteria357** [jpalbert/logitech-webcam-dialog#4]
Hi, thanks for writing this script.  When I run it, the dialog box opens without issue.  when I close it, I get an error in the command line saying "At least one output file must be specified".  Are there some arguments I'm missing when I run the script?  

Thanks

**Comment by jpalbert** [comment]
Run **launch.bat** instead of **webcamdialog.bat** and you won't see the command prompt window and this error on close.

**Comment by hysteria357** [comment]
That did it, thanks!
