### ISSUE TITLE
Persistent changes on the webcam settings

### ISSUE THREAD

**Issue by bitwinkel** [jpalbert/logitech-webcam-dialog#5]
First of all congratulations, great job!
Do you know why webcam settings returns to de predeterminated positions after shutdown the PC?

**Comment by jpalbert** [comment]
Hi! Thank you! Unfortunately, the changes are not persistent using this method. If I have time in the future, I might work on creating a small application where you can save and load presets. I'll let people know if that idea ever come to life. Have a great day!

**Comment by morgenman** [comment]
I would appreciate that. I am not sure how to set settings via command line for ffmpeg otherwise I would write it myself. My webcam makes me look very pink, I always have to set my hue to 35 otherwise it looks like I have a crazy beauty filter on.
