### ISSUE TITLE
Problems with webcam names containing '®' characters

### ISSUE THREAD

**Issue by jpyo0613** [jpalbert/logitech-webcam-dialog#7]
Hello, I don't know if the webcam name has ® characters in it and it doesn't work. Dialog works fine with other webcams, but the "Microsoft® LifeCam HD-3000" webcam doesn't work. Please help me make it work.

![20230203_073459](https://user-images.githubusercontent.com/33045561/216464907-44bb694b-74e7-4acd-a653-0fc18d494a4c.jpg)

When I connect two webcams with the same name, I only want to change the settings of one webcam, but they both change because they both have the same name.
How to solve this part?
Two webcams with the same name changed at the same time, so I searched for another webcam, but... I only have a webcam named "Microsoft® LifeCam HD-3000". However, the dialog does not work because of the '®' character.

**Comment by jpalbert** [comment]
Can you try with the alternative names instead? Should maybe fix both issues:
![image](https://user-images.githubusercontent.com/7884120/218588690-efcbbd66-95be-4ff1-a508-7058595f4ebf.png)

Let me know.

**Comment by jpyo0613** [comment]
Thank you!
